#!/bin/bash
# WAF/OPA False Positive Measurement - Telemetry Setup
# Owner: Worf (Security & Cloud)
# Purpose: Configure Azure Monitor, Log Analytics, and Cosmos DB for 10-day measurement cycle

set -euo pipefail

# Configuration
RESOURCE_GROUP="${RESOURCE_GROUP:-dk8s-security}"
LOCATION="${LOCATION:-eastus2}"
WORKSPACE_NAME="${WORKSPACE_NAME:-dk8s-measurement-workspace}"
COSMOS_ACCOUNT="${COSMOS_ACCOUNT:-dk8s-measurement-db}"
COSMOS_DATABASE="false-positive-measurement"
COSMOS_COLLECTION="classifications"
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting telemetry infrastructure setup..."

# 1. Create Log Analytics Workspace
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Creating Log Analytics workspace: $WORKSPACE_NAME"
WORKSPACE_ID=$(az monitor log-analytics workspace create \
  --resource-group "$RESOURCE_GROUP" \
  --workspace-name "$WORKSPACE_NAME" \
  --location "$LOCATION" \
  --retention-time 30 \
  --query customerId -o tsv)

WORKSPACE_KEY=$(az monitor log-analytics workspace get-shared-keys \
  --resource-group "$RESOURCE_GROUP" \
  --workspace-name "$WORKSPACE_NAME" \
  --query primarySharedKey -o tsv)

echo "✅ Log Analytics workspace created: $WORKSPACE_ID"

# 2. Create Cosmos DB for classification data
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Creating Cosmos DB account: $COSMOS_ACCOUNT"
az cosmosdb create \
  --name "$COSMOS_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --locations regionName="$LOCATION" failoverPriority=0 isZoneRedundant=False \
  --default-consistency-level Session \
  --enable-automatic-failover false \
  --capabilities EnableServerless

# Create database and collection
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Creating database: $COSMOS_DATABASE"
az cosmosdb sql database create \
  --account-name "$COSMOS_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --name "$COSMOS_DATABASE"

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Creating collection: $COSMOS_COLLECTION"
az cosmosdb sql container create \
  --account-name "$COSMOS_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --database-name "$COSMOS_DATABASE" \
  --name "$COSMOS_COLLECTION" \
  --partition-key-path "/requestId" \
  --throughput 400

# Create index for efficient queries
cat > /tmp/indexing-policy.json <<EOF
{
  "indexingMode": "consistent",
  "automatic": true,
  "includedPaths": [
    { "path": "/*" }
  ],
  "excludedPaths": [
    { "path": "/requestBody/*" },
    { "path": "/resourceManifest/*" }
  ],
  "compositeIndexes": [
    [
      { "path": "/timestamp", "order": "descending" },
      { "path": "/classification", "order": "ascending" }
    ],
    [
      { "path": "/ruleId", "order": "ascending" },
      { "path": "/classification", "order": "ascending" }
    ]
  ]
}
EOF

az cosmosdb sql container update \
  --account-name "$COSMOS_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --database-name "$COSMOS_DATABASE" \
  --name "$COSMOS_COLLECTION" \
  --idx @/tmp/indexing-policy.json

echo "✅ Cosmos DB created with optimized indexing"

# 3. Get Cosmos DB connection string
COSMOS_CONNECTION=$(az cosmosdb keys list \
  --name "$COSMOS_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --type connection-strings \
  --query "connectionStrings[0].connectionString" -o tsv)

# 4. Create Azure Monitor Data Collection Rule for WAF
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Creating Data Collection Rule for WAF telemetry"
cat > /tmp/dcr-waf.json <<EOF
{
  "location": "$LOCATION",
  "properties": {
    "dataSources": {
      "extensions": [
        {
          "name": "WAFLogCollection",
          "streams": [
            "Microsoft-FrontdoorWebApplicationFirewallLog"
          ],
          "extensionName": "FrontdoorFirewall"
        }
      ]
    },
    "destinations": {
      "logAnalytics": [
        {
          "workspaceResourceId": "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.OperationalInsights/workspaces/$WORKSPACE_NAME",
          "name": "centralWorkspace"
        }
      ]
    },
    "dataFlows": [
      {
        "streams": [
          "Microsoft-FrontdoorWebApplicationFirewallLog"
        ],
        "destinations": [
          "centralWorkspace"
        ]
      }
    ]
  }
}
EOF

az monitor data-collection rule create \
  --name "dcr-waf-measurement" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --rule-file /tmp/dcr-waf.json

echo "✅ WAF Data Collection Rule created"

# 5. Export configuration for subsequent scripts
cat > measurement-config.env <<EOF
# Generated by 01-setup-telemetry.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
export WORKSPACE_ID="$WORKSPACE_ID"
export WORKSPACE_KEY="$WORKSPACE_KEY"
export WORKSPACE_NAME="$WORKSPACE_NAME"
export COSMOS_CONNECTION="$COSMOS_CONNECTION"
export COSMOS_ACCOUNT="$COSMOS_ACCOUNT"
export COSMOS_DATABASE="$COSMOS_DATABASE"
export COSMOS_COLLECTION="$COSMOS_COLLECTION"
export RESOURCE_GROUP="$RESOURCE_GROUP"
export SUBSCRIPTION_ID="$SUBSCRIPTION_ID"
EOF

chmod 600 measurement-config.env

echo ""
echo "✅ Telemetry infrastructure setup complete!"
echo ""
echo "Configuration saved to: measurement-config.env"
echo "  - Log Analytics Workspace ID: $WORKSPACE_ID"
echo "  - Cosmos DB Account: $COSMOS_ACCOUNT"
echo "  - Database: $COSMOS_DATABASE"
echo "  - Collection: $COSMOS_COLLECTION"
echo ""
echo "Next steps:"
echo "  1. Source configuration: source measurement-config.env"
echo "  2. Deploy WAF policies: ./02-deploy-waf-policies.sh"
echo "  3. Deploy OPA policies: ./03-deploy-opa-policies.sh"
echo ""
