apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squad.fullname" . }}-state
  namespace: {{ .Values.squad.namespace }}
  labels:
    {{- include "squad.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
