apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squad.fullname" . }}
  namespace: {{ .Values.squad.namespace }}
  labels:
    {{- include "squad.labels" . | nindent 4 }}
  {{- if .Values.github.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.github.workloadIdentity.clientId }}
  {{- end }}
