<#
.SYNOPSIS
    Exports daily study plan to Markdown format.

.DESCRIPTION
    Generates a Markdown file with today's study plan and upcoming exam reminders.
    Suitable for posting to Teams, GitHub issues, or viewing in editors.

.PARAMETER SchedulePath
    Path to schedule.yaml file. Defaults to schedule.yaml in script directory.

.PARAMETER OutputPath
    Path for the output Markdown file. Defaults to daily-plan.md in script directory.

.EXAMPLE
    .\Export-StudyPlan.ps1
    Generates daily-plan.md with today's schedule.

.EXAMPLE
    .\Export-StudyPlan.ps1 -OutputPath "C:\plans\today.md"
    Exports to a custom location.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$SchedulePath = "$PSScriptRoot\schedule.yaml",
    
    [Parameter()]
    [string]$OutputPath = "$PSScriptRoot\daily-plan.md"
)

# Get exam schedule
$exams = & "$PSScriptRoot\Get-ExamSchedule.ps1" -SchedulePath $SchedulePath

$today = Get-Date
$todayStr = $today.ToString("dddd, MMMM dd, yyyy")

# Build markdown content
$markdown = @"
# 📚 Daily Study Plan
**Date:** $todayStr

---

"@

# Add urgent exam reminders
$urgentExams = $exams | Where-Object { $_.DaysUntil -ge 0 -and $_.DaysUntil -le 7 } | Sort-Object DaysUntil

if ($urgentExams.Count -gt 0) {
    $markdown += @"
## ⚠️ Upcoming Exams

"@
    
    foreach ($exam in $urgentExams) {
        $daysText = if ($exam.DaysUntil -eq 0) { "**TODAY**" }
                    elseif ($exam.DaysUntil -eq 1) { "**TOMORROW**" }
                    else { "in **$($exam.DaysUntil) days**" }
        
        $markdown += "- 🎯 **$($exam.StudentName)** - $($exam.Subject) $daysText ($($exam.ExamDate.ToString('yyyy-MM-dd')))`n"
    }
    
    $markdown += "`n---`n`n"
}

# Generate today's study sessions
$studyPlan = & "$PSScriptRoot\New-StudyPlan.ps1" -SchedulePath $SchedulePath -DaysAhead 1 -ExcludeShabbat 2>&1 | Out-Null
$studyPlanPath = "$PSScriptRoot\temp-plan.json"

# Get the actual plan by re-running with proper capture
$capturedPlan = & "$PSScriptRoot\New-StudyPlan.ps1" -SchedulePath $SchedulePath -DaysAhead 1 -ExcludeShabbat 2>&1 | 
    Where-Object { $_ -is [System.Collections.Hashtable] } | Select-Object -First 1

$todayKey = $today.ToString("yyyy-MM-dd")

if ($capturedPlan -and $capturedPlan.ContainsKey($todayKey)) {
    $todaySessions = $capturedPlan[$todayKey]
    
    $markdown += @"
## 📖 Today's Study Sessions

"@
    
    $currentStudent = $null
    foreach ($session in $todaySessions) {
        if ($session.StudentName -ne $currentStudent) {
            if ($currentStudent -ne $null) {
                $markdown += "`n"
            }
            $markdown += "### 👤 $($session.StudentName)`n`n"
            $markdown += "| Time | Subject | Topic | Duration | Type |`n"
            $markdown += "|------|---------|-------|----------|------|`n"
            $currentStudent = $session.StudentName
        }
        
        $timeSlot = "16:00"  # Default start time, can be customized
        $markdown += "| $timeSlot | $($session.Subject) | $($session.Topic) | $($session.Duration) min | $($session.SessionType) |`n"
    }
    
    $markdown += "`n"
}
else {
    $markdown += @"
## 🎉 No Study Sessions Today

Great news! No scheduled study sessions for today. Use this time to:
- Review previous material
- Get ahead on homework
- Take a well-deserved break

"@
}

# Add upcoming week preview
$weekAhead = $exams | Where-Object { $_.DaysUntil -gt 0 -and $_.DaysUntil -le 14 } | Sort-Object DaysUntil

if ($weekAhead.Count -gt 0) {
    $markdown += @"
---

## 📅 Next 2 Weeks

"@
    
    foreach ($exam in $weekAhead) {
        $markdown += "- **$($exam.ExamDate.ToString('MMM dd'))** - $($exam.StudentName) - $($exam.Subject) ($($exam.Topics.Count) topics)`n"
    }
}

$markdown += @"

---

*Generated by Kids Study Assistant*  
*Last updated: $($today.ToString('yyyy-MM-dd HH:mm'))*
"@

# Write to file
$markdown | Out-File -FilePath $OutputPath -Encoding UTF8 -Force

Write-Host "✓ Daily study plan exported to: $OutputPath" -ForegroundColor Green
Write-Host "`nPreview:`n"
Write-Host $markdown

return $OutputPath
