# Scheduled Cache Review Automation
# Checks if a cache review is due and creates the issue automatically
# Called by ralph-watch.ps1 monthly

param(
    [switch]$Force  # Create issue even if not due (for testing)
)

$ErrorActionPreference = "Stop"

# Check if it's the first day of the month OR force mode
$today = Get-Date
$isDueDate = ($today.Day -eq 1) -or $Force

if (-not $isDueDate) {
    Write-Host "Cache review not due today (day $($today.Day)). Runs on the 1st of each month."
    exit 0
}

# Determine the review month
$reviewMonth = $today.ToString("MMMM yyyy")
$reviewDate = $today.ToString("MMMM d, yyyy")
$nextMonthDate = $today.AddMonths(1)
$nextReviewDate = Get-Date -Year $nextMonthDate.Year -Month $nextMonthDate.Month -Day 1
$nextReviewDateFormatted = $nextReviewDate.ToString("MMMM d, yyyy")

Write-Host "🗓️  Creating cache review issue for $reviewMonth..." -ForegroundColor Cyan

# Issue body template — use single-quoted here-string (@'...'@) for PS 5.1 compatibility
# PS 5.1 reads UTF-8 files as ANSI, breaking double-quoted here-strings with special chars
$reviewYearMonth = $today.ToString("yyyy-MM")
$issueBody = @'
# FedRAMP Dashboard Cache Configuration Review - {ReviewMonth}

**Review Date:** {ReviewDate} at 10:00 AM PT
**Review Period:** 30 days prior
**Attendees:** Data (Code Expert), Infrastructure Lead, SRE On-Call

---

## Pre-Review Checklist

- [ ] Query Application Insights for 30-day metrics
- [ ] Prepare access pattern analysis
- [ ] Review any open action items from previous month
- [ ] Check for cache-related incidents or alerts

---

## Meeting Agenda

1. **Performance Metrics** (10 min)
   - Cache hit rate: Current vs. SLO (>=70%)
   - Backend query reduction: Current vs. target (80-85%)
   - P95 latency: Current vs. target (<500ms)

2. **Access Pattern Analysis** (10 min)
   - Top query combinations
   - Traffic patterns (peak/off-peak/weekend)
   - Unique parameter combinations

3. **Incidents & Anomalies** (5 min)
   - Alert history (cache hit rate < 70%)
   - Unusual patterns or traffic spikes
   - False positive analysis

4. **Recommendations & Action Items** (5 min)
   - Cache configuration adjustments needed
   - Monitoring improvements
   - Documentation updates

---

## Application Insights Queries

### 30-Day Cache Hit Rate
```kusto
requests
| where timestamp > ago(30d)
| where name has "compliance"
| extend IsCacheHit = iff(duration < 100, 1, 0)
| summarize
    TotalRequests = count(),
    CacheHits = sum(IsCacheHit),
    CacheMisses = sum(1 - IsCacheHit),
    AvgDuration = avg(duration),
    P95Duration = percentile(duration, 95),
    P99Duration = percentile(duration, 99)
| extend CacheHitRate = round((CacheHits * 100.0) / TotalRequests, 2)
| project
    TotalRequests,
    CacheHits,
    CacheMisses,
    CacheHitRate,
    AvgDuration = round(AvgDuration, 2),
    P95Duration = round(P95Duration, 2),
    P99Duration = round(P99Duration, 2)
```

---

## Deliverables

After the review meeting:

1. **Create Review Summary:** `docs/fedramp/cache-reviews/{ReviewYearMonth}.md`
2. **Update Historical Tracking:** `docs/fedramp/cache-reviews/README.md`
3. **File Action Item Issues** for any configuration changes
4. **Schedule Next Review:** {NextReviewDate}

---

## Reference Documentation

- **Cache SLI:** `docs/fedramp-dashboard-cache-sli.md`
- **Review Template:** `docs/fedramp/cache-reviews/template.md`
- **Deployment Guide:** `docs/fedramp/cache-alert-deployment-guide.md`

---

**Created:** Auto-generated by scheduled-cache-review.ps1
**Owner:** Data (Code Expert)
'@

# Replace placeholders with actual values
$issueBody = $issueBody.Replace('{ReviewMonth}', $reviewMonth).Replace('{ReviewDate}', $reviewDate).Replace('{NextReviewDate}', $nextReviewDateFormatted).Replace('{ReviewYearMonth}', $reviewYearMonth)

# Create the issue using gh CLI
$issueTitle = "Cache Review: $reviewMonth"

try {
    $result = gh issue create `
        --repo tamirdresher_microsoft/tamresearch1 `
        --title $issueTitle `
        --body $issueBody `
        --label "squad,squad:data,squad:belanna" `
        --assignee "@me" | Out-String
    
    Write-Host "✅ Issue created: $result" -ForegroundColor Green
    
    # Extract issue number from the result (format: https://github.com/owner/repo/issues/123)
    if ($result -match '/issues/(\d+)') {
        $issueNumber = $Matches[1]
        Write-Host "📋 Issue #$issueNumber created successfully"
        
        # Add to project board as Todo
        Write-Host "📊 Adding to project board..."
        $itemId = gh project item-add 1 --owner tamirdresher_microsoft --url "https://github.com/tamirdresher_microsoft/tamresearch1/issues/$issueNumber" --format json | ConvertFrom-Json | Select-Object -ExpandProperty id
        
        # Set status to Todo
        gh project item-edit --project-id PVT_kwHOC0L5c84BRG-P --id $itemId --field-id PVTSSF_lAHOC0L5c84BRG-Pzg_CIuc --single-select-option-id 0de780a1
        Write-Host "✅ Added to project board (Todo column)" -ForegroundColor Green
    }
    
    exit 0
} catch {
    Write-Host "❌ Failed to create issue: $_" -ForegroundColor Red
    exit 1
}
