#!/bin/bash
# compliance-delta-report.sh
# Generates FedRAMP compliance delta report for Helm/Kustomize changes
# Part of Issue #75: Drift Detection for Helm/Kustomize Configurations

set -e

echo "=== Generating FedRAMP Compliance Delta Report ==="

# Load drift detection results
if [ -f /tmp/drift-detection.env ]; then
  source /tmp/drift-detection.env
else
  HELM_CHANGES=""
  KUSTOMIZE_CHANGES=""
fi

# Generate report
cat > /tmp/compliance-delta.md << EOF
# FedRAMP Compliance Delta Report

**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Generated by:** Drift Detection System (Issue #75)

## Configuration Changes Detected

### Helm Chart Changes
EOF

if [[ -n "$HELM_CHANGES" ]]; then
  echo "$HELM_CHANGES" | sed 's/^/- /' >> /tmp/compliance-delta.md
else
  echo "_No Helm changes detected_" >> /tmp/compliance-delta.md
fi

cat >> /tmp/compliance-delta.md << EOF

### Kustomize Overlay Changes
EOF

if [[ -n "$KUSTOMIZE_CHANGES" ]]; then
  echo "$KUSTOMIZE_CHANGES" | sed 's/^/- /' >> /tmp/compliance-delta.md
else
  echo "_No Kustomize changes detected_" >> /tmp/compliance-delta.md
fi

cat >> /tmp/compliance-delta.md << EOF

## Security Field Analysis

### Validation Results Summary

EOF

# Check for validation results
if [ -d /tmp/validation-results ] && [ "$(ls -A /tmp/validation-results)" ]; then
  echo "The following security-relevant fields were detected:" >> /tmp/compliance-delta.md
  echo "" >> /tmp/compliance-delta.md
  
  for result_file in /tmp/validation-results/*.txt; do
    if [ -s "$result_file" ]; then
      filename=$(basename "$result_file")
      echo "**$filename:**" >> /tmp/compliance-delta.md
      echo '```' >> /tmp/compliance-delta.md
      head -n 20 "$result_file" >> /tmp/compliance-delta.md
      echo '```' >> /tmp/compliance-delta.md
      echo "" >> /tmp/compliance-delta.md
    fi
  done
else
  echo "_No security field changes detected in rendered manifests_" >> /tmp/compliance-delta.md
  echo "" >> /tmp/compliance-delta.md
fi

cat >> /tmp/compliance-delta.md << EOF

## Control Re-Validation Checklist

| Control | Description | Status | Notes |
|---------|-------------|--------|-------|
| SC-7 | Boundary Protection | ⏳ | NetworkPolicy validation required |
| SC-8 | Transmission Confidentiality | ⏳ | TLS enforcement check required |
| SI-3 | Malicious Code Protection | ⏳ | OPA policy validation required |
| SI-2 | Flaw Remediation | ⏳ | Trivy scan required for image changes |
| CM-3 | Configuration Change Control | ⏳ | Helm/Kustomize diff analysis required |
| CM-7 | Least Functionality | ⏳ | Security context validation required |

## Recommendations

### Next Steps

1. **Run Full FedRAMP Test Suite:**
   - \`tests/fedramp-validation/network-policy-tests.sh\`
   - \`tests/fedramp-validation/opa-policy-tests.sh\`
   - \`tests/fedramp-validation/waf-rule-tests.sh\`

2. **Review Rendered Manifests:**
   - Check \`/tmp/rendered-current/\` for configuration changes
   - Validate security contexts and NetworkPolicies

3. **Manual Review (if WARNING level):**
   - Verify chart version bumps don't introduce vulnerabilities
   - Confirm Kustomize patches don't weaken controls

### Approval Criteria

- ✅ **Auto-Approve:** No security field changes detected
- ⚠ **Manual Review:** Security fields changed but within thresholds
- ❌ **Block:** CRITICAL controls disabled (NetworkPolicy, TLS, privileged containers)

---

**Documentation:** \`docs/fedramp/drift-detection-helm-kustomize.md\`  
**Related Issues:** #75, #72, #73  
**Owner:** B'Elanna (Infrastructure Expert)
EOF

echo "✓ Compliance delta report generated: /tmp/compliance-delta.md"
cat /tmp/compliance-delta.md
