name: Post Comment (Reusable)

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'Issue or PR number to comment on'
        required: true
        type: number
      body:
        description: 'Comment body (markdown supported)'
        required: true
        type: string

jobs:
  post:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Post comment
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue_number }},
              body: `${{ inputs.body }}`
            });
